name: Tests
on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        mongoid: [4, 5, 6, 7, 8, 9 HEAD]
        ruby: [3.2]
        include:
          - mongoid: 9
            ruby: 3.1
          - mongoid: 9
            ruby: 3.2
          - mongoid: 9
            ruby: 3.3

    runs-on: ubuntu-latest
    steps:
      - id: mongodb
        name: Start MongoDB
        uses: mongodb-labs/drivers-evergreen-tools@master
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: RSpec
        run: bundle exec rake
        env:
          MONGODB_URI: "${{ steps.mongodb.outputs.cluster-uri }}"
